# Generated by Django 5.1.4 on 2024-12-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitation',
            name='reset_counters_start_time',
            field=models.CharField(blank=True, max_length=67, null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='uptime_limit',
            field=models.CharField(default='30d', help_text='30m (30 minutes), 45d (45 days), 0 (no expiration)', max_length=67),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trans_end',
            field=models.CharField(blank=True, max_length=67, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trans_start',
            field=models.CharField(blank=True, max_length=67, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='validity',
            field=models.CharField(default='30d', help_text='30m (30 minutes), 45d (45 days), 15d 00:45:00 (15 days, 0 hours, 45 minutes, and 0 seconds, 0 (no expiration)', max_length=67, verbose_name='validity'),
        ),
        migrations.AlterField(
            model_name='session',
            name='download',
            field=models.CharField(max_length=67, verbose_name='Download'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ended',
            field=models.CharField(blank=True, max_length=67, null=True, verbose_name='Ended'),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_accounting_packet',
            field=models.CharField(blank=True, max_length=67, null=True, verbose_name='Last Accounting Packet'),
        ),
        migrations.AlterField(
            model_name='session',
            name='started',
            field=models.CharField(blank=True, max_length=67, null=True, verbose_name='Started'),
        ),
        migrations.AlterField(
            model_name='session',
            name='upload',
            field=models.CharField(max_length=67, verbose_name='Upload'),
        ),
        migrations.AlterField(
            model_name='session',
            name='uptime',
            field=models.CharField(max_length=67, verbose_name='Uptime'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='end_time',
            field=models.CharField(blank=True, max_length=67, null=True, verbose_name='end time'),
        ),
    ]
